[workspace]
members = [
    "edgelet-client",
    "mqtt3",
    "mqtt-broker",
    "mqtt-broker-tests-util",
    "mqtt-edgehub",
    "mqtt-generic",
    "mqtt-policy",
    "mqttd",
    "policy",
    "norcim"
]

[profile.release]
debug = true
